
# redirect from old blogger urls to new 11ty urls
redirects = [
  {from="/kyle", to="https://kylemit.dev/"},
  {from="/james", to="https://jamesmit.dev/"},
  {from="/r/google-icons", to="https://github.com/KyleMit/CustomizeTheWeb/blob/master/Scripts/restore-google-icons.user.js"}
]
